- name: Adds nginx ppa
  apt_repository:
    repo=ppa:nginx/stable

- name: Adds PPA key
  apt_key: 
    url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x00A6F0A3C300EE8C
    state=present

- name: Installs nginx
  apt:
    pkg=nginx-full
    state=latest
  register: just_installed

- name: Writes nginx.conf
  template: 
    src="../templates/nginx.j2"
    dest=/etc/nginx/nginx.conf
    validate='nginx -tc %s'
  notify:
  - Restart nginx

- name: Replaces nginx default server
  template:
    src="../templates/default.j2"
    dest=/etc/nginx/sites-available/default
  when: nginx_add_default
  notify:
    - Restart nginx

