- name: Installs nginx
  apt:
    pkg: nginx-full
    state: latest
    update_cache: yes
  register: __nginx_just_installed

- name: Writes nginx.conf
  template:
    src: "../templates/nginx.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart nginx

- name: Removes nginx default server link
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Removes nginx default server
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  notify: Restart nginx

- name: Writes nginx.conf
  template:
    src: "../templates/nginx.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Reload nginx

- name: Replaces logrotate entry
  template:
    src: logrotate_nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: 0644

- name: Enables nginx at start
# service module is severely broken on 14.04
#  service: name=nginx enabled=yes
  command: update-rc.d nginx defaults
  when: __nginx_just_installed|changed
  notify: Restart nginx
